# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  WrapperApp_config = debug

else ifeq ($(config),release)
  WrapperApp_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := WrapperApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

WrapperApp:
ifneq (,$(WrapperApp_config))
	@echo "==== Building WrapperApp ($(WrapperApp_config)) ===="
	@${MAKE} --no-print-directory -C . -f WrapperApp.make config=$(WrapperApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f WrapperApp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   WrapperApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"